// AUTO-GENERATED by scripts/generate-meta.ts — DO NOT EDIT BY HAND.
// Run `pnpm gen:meta` after changing any equation's metadata fields.
import type { EquationMeta } from './types';

export const meta: EquationMeta[] = [
  {
    "id": "pythagoras",
    "name": "Pythagorean Theorem",
    "nickname": "the first deep theorem of mathematics",
    "canonicalLatex": "a^2 + b^2 = c^2",
    "canonicalAlt": "a squared plus b squared equals c squared",
    "fields": [
      "geometry",
      "mathematics"
    ],
    "era": {
      "display": "~530 BCE",
      "sortKey": -530
    },
    "oneLine": "In any right triangle, the squares on the two short sides add up to the square on the longest.",
    "significance": "It is the bridge between geometry and arithmetic: lengths (geometry) obey an algebraic law. It defines distance itself — the Euclidean metric and its generalizations underpin coordinate geometry, trigonometry, vector spaces, and ultimately the spacetime interval of relativity. Its discovery of incommensurable lengths (√2) forced the first crisis and refinement in the idea of number.",
    "symbols": [
      {
        "symbol": "a",
        "name": "leg",
        "meaning": "length of one side adjacent to the right angle",
        "units": "length"
      },
      {
        "symbol": "b",
        "name": "leg",
        "meaning": "length of the other side adjacent to the right angle",
        "units": "length"
      },
      {
        "symbol": "c",
        "name": "hypotenuse",
        "meaning": "length of the side opposite the right angle (the longest)",
        "units": "length"
      },
      {
        "symbol": "\\mathbf{x}",
        "name": "vector",
        "meaning": "a point/displacement with components xᵢ",
        "units": "length"
      },
      {
        "symbol": "ds",
        "name": "line element",
        "meaning": "infinitesimal distance between nearby points",
        "units": "length"
      }
    ],
    "connections": [
      {
        "toId": "einstein-field",
        "relationship": "is the flat-space limit of the metric in"
      },
      {
        "toId": "fourier",
        "relationship": "underlies the orthogonality / Parseval relation behind"
      },
      {
        "toId": "normal-distribution",
        "relationship": "supplies the sum-of-squares geometry used by"
      }
    ]
  },
  {
    "id": "logarithms",
    "name": "Logarithms",
    "nickname": "the invention that gave astronomers a longer life",
    "canonicalLatex": "\\log(xy) = \\log x + \\log y",
    "canonicalAlt": "log of x times y equals log of x plus log of y",
    "fields": [
      "mathematics",
      "analysis"
    ],
    "era": {
      "display": "1614",
      "sortKey": 1614
    },
    "oneLine": "A way to turn multiplication into addition — and to measure things that span enormous ranges.",
    "significance": "Logarithms collapse multiplication into addition, which before electronic computers made long astronomical and navigational calculations feasible (and gave us the slide rule). Conceptually they are the inverse of exponential growth and the natural language of anything that grows by ratios: pitch, pH, magnitude, decibels, information. The natural logarithm and its derivative 1/x sit at the foundation of calculus and analysis.",
    "symbols": [
      {
        "symbol": "x",
        "name": "argument",
        "meaning": "a positive number whose logarithm is taken",
        "units": "dimensionless"
      },
      {
        "symbol": "b",
        "name": "base",
        "meaning": "the number being raised to a power; common choices 10, e, 2",
        "units": "dimensionless"
      },
      {
        "symbol": "\\log_b",
        "name": "logarithm base b",
        "meaning": "the exponent to which b must be raised to get the argument",
        "units": "dimensionless"
      },
      {
        "symbol": "\\ln",
        "name": "natural logarithm",
        "meaning": "logarithm base e ≈ 2.71828",
        "units": "dimensionless"
      },
      {
        "symbol": "e",
        "name": "Euler's number",
        "meaning": "base of natural growth, ≈ 2.71828",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "euler-identity",
        "relationship": "has the complex logarithm whose principal value is"
      },
      {
        "toId": "shannon-entropy",
        "relationship": "supplies the additive-over-independence log used in"
      },
      {
        "toId": "derivative",
        "relationship": "introduces 1/x as the antiderivative completing"
      }
    ]
  },
  {
    "id": "derivative",
    "name": "The Derivative (Calculus)",
    "nickname": "the mathematics of instantaneous change",
    "canonicalLatex": "f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}",
    "canonicalAlt": "f prime of x equals the limit as h goes to zero of the quantity f of x plus h minus f of x, all over h",
    "fields": [
      "analysis",
      "mathematics"
    ],
    "era": {
      "display": "1666–1684",
      "sortKey": 1666
    },
    "oneLine": "The exact rate at which something changes at a single instant — the slope of a curve at a point.",
    "significance": "The derivative makes \"instantaneous rate of change\" precise, resolving Zeno-style paradoxes about motion. It is the engine of physics (velocity, acceleration, every law written as a differential equation), of optimization (maxima where the derivative vanishes), and of approximation (linearization). Together with its inverse, the integral, it is one half of the most consequential idea in applied mathematics.",
    "symbols": [
      {
        "symbol": "f",
        "name": "function",
        "meaning": "the quantity whose rate of change we study",
        "units": "any"
      },
      {
        "symbol": "x",
        "name": "independent variable",
        "meaning": "the input (often time or position)",
        "units": "any"
      },
      {
        "symbol": "h",
        "name": "increment",
        "meaning": "a small change in x that is sent to zero",
        "units": "same as x"
      },
      {
        "symbol": "f'",
        "name": "derivative",
        "meaning": "the instantaneous rate of change of f with respect to x",
        "units": "units of f per unit of x"
      },
      {
        "symbol": "\\frac{df}{dx}",
        "name": "Leibniz derivative",
        "meaning": "same object, emphasizing the ratio of small changes",
        "units": "units of f per unit of x"
      }
    ],
    "connections": [
      {
        "toId": "logistic-map",
        "relationship": "provides the stability test $|f'|<1$ used by"
      },
      {
        "toId": "euler-lagrange",
        "relationship": "is promoted to a functional derivative in"
      },
      {
        "toId": "black-scholes",
        "relationship": "supplies the partial derivatives (the Greeks) appearing in"
      }
    ]
  },
  {
    "id": "euler-identity",
    "name": "Euler's Identity",
    "nickname": "the most beautiful equation in mathematics",
    "canonicalLatex": "e^{i\\pi} + 1 = 0",
    "canonicalAlt": "e to the power i pi, plus one, equals zero",
    "fields": [
      "mathematics",
      "analysis"
    ],
    "era": {
      "display": "1748",
      "sortKey": 1748
    },
    "oneLine": "A single line tying together five fundamental constants — 0, 1, e, i, and π — through one rotation.",
    "significance": "Euler’s identity is the special case θ = π of Euler’s formula, which says that exponentiating an imaginary number traces the unit circle. That formula is the hinge between exponential growth and rotation/oscillation, making complex exponentials the universal language of waves, AC circuits, signal processing, and quantum amplitudes. The identity itself is celebrated because it unites the additive (0,1), the geometric (π), the analytic (e), and the algebraic (i) in one relation.",
    "symbols": [
      {
        "symbol": "e",
        "name": "Euler's number",
        "meaning": "base of natural exponentiation, ≈ 2.71828",
        "units": "dimensionless"
      },
      {
        "symbol": "i",
        "name": "imaginary unit",
        "meaning": "a number with i² = −1",
        "units": "dimensionless"
      },
      {
        "symbol": "\\pi",
        "name": "pi",
        "meaning": "half-turn in radians; ratio of circumference to diameter",
        "units": "radians (dimensionless)"
      },
      {
        "symbol": "\\theta",
        "name": "angle",
        "meaning": "rotation angle in radians",
        "units": "radians"
      }
    ],
    "connections": [
      {
        "toId": "logarithms",
        "relationship": "is the principal value of the complex logarithm from"
      },
      {
        "toId": "fourier",
        "relationship": "provides the rotating basis functions e^{iθ} used by"
      },
      {
        "toId": "maxwell",
        "relationship": "is the U(1) gauge symmetry whose gauging yields"
      }
    ]
  },
  {
    "id": "fourier",
    "name": "The Fourier Transform",
    "nickname": "the mathematical prism",
    "canonicalLatex": "\\hat f(\\xi)=\\int_{-\\infty}^{\\infty} f(x)\\,e^{-2\\pi i x\\xi}\\,dx",
    "canonicalAlt": "f hat of xi equals the integral over all x of f of x times e to the minus two pi i x xi, d x",
    "fields": [
      "mathematics",
      "analysis"
    ],
    "era": {
      "display": "1822",
      "sortKey": 1822
    },
    "oneLine": "Splits any signal into the pure frequencies that compose it — like a prism splitting light.",
    "significance": "The Fourier transform expresses a function as a superposition of pure oscillations, turning differentiation and convolution into simple multiplication. It is the backbone of signal and image processing (JPEG, MP3), the spectral method for PDEs, the uncertainty principle, diffraction and crystallography, and the very notion of frequency content. The Fast Fourier Transform made it computationally ubiquitous, arguably one of the most important algorithms ever devised.",
    "symbols": [
      {
        "symbol": "f",
        "name": "signal",
        "meaning": "the function being analyzed (in time or space)",
        "units": "any"
      },
      {
        "symbol": "\\hat f",
        "name": "spectrum",
        "meaning": "the transform: amplitude/phase at each frequency",
        "units": "units of f × units of x"
      },
      {
        "symbol": "\\xi",
        "name": "frequency",
        "meaning": "cycles per unit of x (ordinary frequency convention)",
        "units": "1/units of x"
      },
      {
        "symbol": "x",
        "name": "variable",
        "meaning": "time or position",
        "units": "any"
      },
      {
        "symbol": "i",
        "name": "imaginary unit",
        "meaning": "i² = −1, carrying phase via e^{iθ}",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "euler-identity",
        "relationship": "uses the rotating exponentials e^{iθ} of"
      },
      {
        "toId": "heat-equation",
        "relationship": "diagonalizes the derivatives of"
      },
      {
        "toId": "schrodinger",
        "relationship": "relates position and momentum bases of"
      },
      {
        "toId": "pythagoras",
        "relationship": "preserves energy by the Parseval relation, a form of"
      }
    ]
  },
  {
    "id": "gravitation",
    "name": "Newton's Universal Gravitation",
    "nickname": "the law that married the apple and the Moon",
    "canonicalLatex": "F = G\\dfrac{m_1 m_2}{r^2}",
    "canonicalAlt": "F equals G times m one m two divided by r squared",
    "fields": [
      "physics",
      "mechanics"
    ],
    "era": {
      "display": "1687",
      "sortKey": 1687
    },
    "oneLine": "Every mass attracts every other with a force that grows with their masses and fades as the square of distance.",
    "significance": "Newton’s gravitation was the first law to unify the heavens and the earth: the same force that drops an apple holds the Moon in orbit. It explained Kepler’s planetary laws, the tides, and the shape of the Earth, and made astronomy quantitative and predictive — enabling the discovery of Neptune from orbital anomalies. It stood essentially unchallenged for over two centuries until general relativity refined it.",
    "symbols": [
      {
        "symbol": "F",
        "name": "gravitational force",
        "meaning": "attractive force between the two masses",
        "units": "N"
      },
      {
        "symbol": "G",
        "name": "gravitational constant",
        "meaning": "universal constant of gravitation, 6.674×10⁻¹¹",
        "units": "N·m²/kg²"
      },
      {
        "symbol": "m_1",
        "name": "first mass",
        "meaning": "gravitational mass of body 1",
        "units": "kg"
      },
      {
        "symbol": "m_2",
        "name": "second mass",
        "meaning": "gravitational mass of body 2",
        "units": "kg"
      },
      {
        "symbol": "r",
        "name": "separation",
        "meaning": "distance between the centers of the masses",
        "units": "m"
      },
      {
        "symbol": "\\Phi",
        "name": "gravitational potential",
        "meaning": "potential energy per unit mass",
        "units": "J/kg = m²/s²"
      }
    ],
    "connections": [
      {
        "toId": "newton-second",
        "relationship": "is the force fed into the equation of motion"
      },
      {
        "toId": "coulomb",
        "relationship": "shares the identical inverse-square mathematical form with"
      },
      {
        "toId": "einstein-field",
        "relationship": "is the weak-field Newtonian limit of"
      }
    ]
  },
  {
    "id": "newton-second",
    "name": "Newton's Second Law",
    "nickname": "the equation of motion",
    "canonicalLatex": "\\vec F = m\\vec a",
    "canonicalAlt": "vector F equals m times vector a",
    "fields": [
      "mechanics",
      "physics"
    ],
    "era": {
      "display": "1687",
      "sortKey": 1687
    },
    "oneLine": "Force equals mass times acceleration — the rule that turns causes (forces) into motion.",
    "significance": "Newton’s second law is the prototype of a physical law as a differential equation: specify the forces, and the future motion is determined. It launched deterministic, predictive science — the same law sends a cannonball downrange and a spacecraft to Saturn. It defines what we mean by force and (inertial) mass, and it remains the working tool of engineering even though relativity and quantum mechanics bound its domain.",
    "symbols": [
      {
        "symbol": "\\vec F",
        "name": "net force",
        "meaning": "vector sum of all forces acting on the body",
        "units": "N = kg·m/s²"
      },
      {
        "symbol": "m",
        "name": "mass",
        "meaning": "inertial mass — resistance to acceleration",
        "units": "kg"
      },
      {
        "symbol": "\\vec a",
        "name": "acceleration",
        "meaning": "rate of change of velocity",
        "units": "m/s²"
      },
      {
        "symbol": "\\vec p",
        "name": "momentum",
        "meaning": "mass times velocity, m·v",
        "units": "kg·m/s"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "the independent variable of motion",
        "units": "s"
      }
    ],
    "connections": [
      {
        "toId": "gravitation",
        "relationship": "supplies the force that, fed into, gives orbital motion via"
      },
      {
        "toId": "euler-lagrange",
        "relationship": "is equivalent for conservative forces to"
      },
      {
        "toId": "mass-energy",
        "relationship": "is the low-speed limit of the relativistic dynamics behind"
      },
      {
        "toId": "schrodinger",
        "relationship": "emerges as the classical (Ehrenfest) limit of"
      }
    ]
  },
  {
    "id": "wave-equation",
    "name": "The Wave Equation",
    "nickname": "the equation of everything that ripples",
    "canonicalLatex": "\\dfrac{\\partial^2 u}{\\partial t^2} = c^2\\dfrac{\\partial^2 u}{\\partial x^2}",
    "canonicalAlt": "the second partial derivative of u with respect to t equals c squared times the second partial derivative of u with respect to x",
    "fields": [
      "pde",
      "physics"
    ],
    "era": {
      "display": "1746",
      "sortKey": 1746
    },
    "oneLine": "A single equation governing how disturbances — on strings, in air, in light — travel at a fixed speed.",
    "significance": "The wave equation is the universal template for propagation: the same second-order PDE describes a plucked string, sound, water ripples, seismic waves, and electromagnetic radiation. Its solutions introduced normal modes and superposition (the seed of Fourier analysis and of quantum states), and its Lorentz-invariant form pointed directly at special relativity. It is the prototype of a hyperbolic PDE, with a finite signal speed and clean causal structure.",
    "symbols": [
      {
        "symbol": "u",
        "name": "displacement / field",
        "meaning": "the disturbance (string height, pressure, field strength)",
        "units": "varies (e.g. m)"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "the time coordinate",
        "units": "s"
      },
      {
        "symbol": "x",
        "name": "position",
        "meaning": "the spatial coordinate (1-D)",
        "units": "m"
      },
      {
        "symbol": "c",
        "name": "wave speed",
        "meaning": "speed at which disturbances propagate",
        "units": "m/s"
      },
      {
        "symbol": "\\nabla^2",
        "name": "Laplacian",
        "meaning": "sum of second spatial derivatives (curvature in space)",
        "units": "1/m²"
      }
    ],
    "connections": [
      {
        "toId": "maxwell",
        "relationship": "is derived as the wave equation for the fields of"
      },
      {
        "toId": "fourier",
        "relationship": "is solved by the mode superposition of"
      },
      {
        "toId": "schrodinger",
        "relationship": "shares wave structure but is first-order in time, unlike"
      },
      {
        "toId": "kdv",
        "relationship": "is the linear limit of the nonlinear wave dynamics in"
      }
    ]
  },
  {
    "id": "ideal-gas",
    "name": "The Ideal Gas Law",
    "nickname": "the bridge from atoms to thermometers",
    "canonicalLatex": "PV = nRT",
    "canonicalAlt": "P times V equals n times R times T",
    "fields": [
      "thermodynamics",
      "chemistry"
    ],
    "era": {
      "display": "1834",
      "sortKey": 1834
    },
    "oneLine": "Pressure, volume, and temperature of a gas are locked together: squeeze or heat it and the other two must respond.",
    "significance": "The ideal gas law unifies the separate empirical laws of Boyle, Charles, and Avogadro into one relation and defines the absolute (Kelvin) temperature scale. It is the simplest equation of state and the workhorse of chemistry, meteorology, and engineering. Crucially, it is *derivable* from the kinetic theory of atoms, making it a historic empirical bridge between the macroscopic world of gauges and thermometers and the microscopic world of molecules in motion.",
    "symbols": [
      {
        "symbol": "P",
        "name": "pressure",
        "meaning": "force per unit area exerted by the gas",
        "units": "Pa = N/m²"
      },
      {
        "symbol": "V",
        "name": "volume",
        "meaning": "volume occupied by the gas",
        "units": "m³"
      },
      {
        "symbol": "n",
        "name": "amount",
        "meaning": "number of moles of gas",
        "units": "mol"
      },
      {
        "symbol": "R",
        "name": "gas constant",
        "meaning": "universal gas constant, 8.314",
        "units": "J/(mol·K)"
      },
      {
        "symbol": "T",
        "name": "temperature",
        "meaning": "absolute temperature",
        "units": "K"
      },
      {
        "symbol": "N",
        "name": "molecule count",
        "meaning": "number of gas molecules",
        "units": "dimensionless"
      },
      {
        "symbol": "k_B",
        "name": "Boltzmann constant",
        "meaning": "R per molecule, 1.381×10⁻²³",
        "units": "J/K"
      }
    ],
    "connections": [
      {
        "toId": "boltzmann-entropy",
        "relationship": "shares the kinetic/statistical foundation with"
      },
      {
        "toId": "boltzmann-transport",
        "relationship": "is the equilibrium limit of the gas dynamics in"
      },
      {
        "toId": "maxwell",
        "relationship": "has molecular speeds set by the same Maxwell distribution kin to"
      }
    ]
  },
  {
    "id": "coulomb",
    "name": "Coulomb's Law",
    "nickname": "gravitation’s electric twin",
    "canonicalLatex": "F = k\\dfrac{q_1 q_2}{r^2}",
    "canonicalAlt": "F equals k times q one q two divided by r squared",
    "fields": [
      "electromagnetism",
      "physics"
    ],
    "era": {
      "display": "1785",
      "sortKey": 1785
    },
    "oneLine": "Like charges repel, opposites attract, with a force that fades as the square of distance — just like gravity.",
    "significance": "Coulomb’s law quantifies the electric force, the dominant interaction of everyday matter: it binds electrons to nuclei, atoms into molecules, and molecules into solids and living tissue. Sharing gravity’s inverse-square form, it became the entry point to electromagnetism and, through Gauss’s law, to Maxwell’s field theory. Its enormous strength relative to gravity (≈10³⁹×) explains why bulk matter is held together electrically.",
    "symbols": [
      {
        "symbol": "F",
        "name": "electric force",
        "meaning": "force between the two charges (repulsive if like-signed)",
        "units": "N"
      },
      {
        "symbol": "k",
        "name": "Coulomb constant",
        "meaning": "1/(4πε₀) ≈ 8.99×10⁹",
        "units": "N·m²/C²"
      },
      {
        "symbol": "q_1",
        "name": "first charge",
        "meaning": "electric charge of body 1 (signed)",
        "units": "C"
      },
      {
        "symbol": "q_2",
        "name": "second charge",
        "meaning": "electric charge of body 2 (signed)",
        "units": "C"
      },
      {
        "symbol": "r",
        "name": "separation",
        "meaning": "distance between the point charges",
        "units": "m"
      },
      {
        "symbol": "\\varepsilon_0",
        "name": "permittivity of free space",
        "meaning": "electric constant, 8.854×10⁻¹²",
        "units": "F/m"
      },
      {
        "symbol": "\\vec E",
        "name": "electric field",
        "meaning": "force per unit charge at a point",
        "units": "N/C = V/m"
      }
    ],
    "connections": [
      {
        "toId": "gravitation",
        "relationship": "shares the identical inverse-square form with"
      },
      {
        "toId": "maxwell",
        "relationship": "is the electrostatic special case (Gauss’s law) of"
      },
      {
        "toId": "euler-identity",
        "relationship": "arises from the U(1) gauge symmetry of"
      }
    ]
  },
  {
    "id": "euler-lagrange",
    "name": "The Euler–Lagrange Equation",
    "nickname": "nature’s optimization rule",
    "canonicalLatex": "\\dfrac{d}{dt}\\dfrac{\\partial L}{\\partial\\dot q}-\\dfrac{\\partial L}{\\partial q}=0",
    "canonicalAlt": "the time derivative of the partial of L with respect to q-dot, minus the partial of L with respect to q, equals zero",
    "fields": [
      "physics",
      "mathematics"
    ],
    "era": {
      "display": "1755",
      "sortKey": 1755
    },
    "oneLine": "The condition a path must satisfy to make a quantity (like action) as small — or stationary — as possible.",
    "significance": "The Euler–Lagrange equation is the master tool of the calculus of variations: it converts \"find the curve that minimizes this integral\" into a differential equation. Through Hamilton’s principle of stationary action it reformulates all of mechanics from a single scalar, the Lagrangian, and via Noether’s theorem ties symmetries to conservation laws. The same equation governs light rays (Fermat), optimal shapes, fields, and is the classical backbone of the path-integral formulation of quantum mechanics.",
    "symbols": [
      {
        "symbol": "L",
        "name": "Lagrangian",
        "meaning": "a scalar function of state, usually kinetic minus potential energy T − V",
        "units": "J (energy)"
      },
      {
        "symbol": "q",
        "name": "generalized coordinate",
        "meaning": "any variable describing configuration (angle, length, field value)",
        "units": "varies"
      },
      {
        "symbol": "\\dot q",
        "name": "generalized velocity",
        "meaning": "time derivative of q",
        "units": "varies/s"
      },
      {
        "symbol": "S",
        "name": "action",
        "meaning": "the time-integral of the Lagrangian along a path",
        "units": "J·s"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "the integration variable (or a path parameter)",
        "units": "s"
      }
    ],
    "connections": [
      {
        "toId": "newton-second",
        "relationship": "reproduces, for $L=T-V$, the dynamics of"
      },
      {
        "toId": "derivative",
        "relationship": "generalizes to functionals the notion of vanishing derivative from"
      },
      {
        "toId": "maxwell",
        "relationship": "is derived from a Lagrangian density for the fields of"
      },
      {
        "toId": "einstein-field",
        "relationship": "follows from varying the Einstein–Hilbert action, giving"
      }
    ]
  },
  {
    "id": "maxwell",
    "name": "Maxwell's Equations",
    "nickname": "the equations that lit up the world",
    "canonicalLatex": "\\nabla\\!\\cdot\\!\\vec E=\\rho/\\varepsilon_0,\\ \\nabla\\!\\cdot\\!\\vec B=0,\\ \\nabla\\!\\times\\!\\vec E=-\\partial_t\\vec B,\\ \\nabla\\!\\times\\!\\vec B=\\mu_0\\vec J+\\mu_0\\varepsilon_0\\partial_t\\vec E",
    "canonicalAlt": "divergence of E equals rho over epsilon-zero; divergence of B equals zero; curl of E equals minus the time derivative of B; curl of B equals mu-zero J plus mu-zero epsilon-zero times the time derivative of E",
    "fields": [
      "electromagnetism",
      "physics"
    ],
    "era": {
      "display": "1865",
      "sortKey": 1865
    },
    "oneLine": "Four equations that tie together all of electricity, magnetism, and light — and predict electromagnetic waves.",
    "significance": "Maxwell’s equations unified electricity and magnetism into a single field theory and revealed that light itself is an electromagnetic wave, traveling at a speed fixed by two electric/magnetic constants. They were the first relativistic field theory (their symmetry is Lorentz, not Galilean), directly inspiring special relativity, and the first gauge theory, the template for the entire Standard Model. Practically, they underlie all of electrical engineering, radio, optics, and modern communications.",
    "symbols": [
      {
        "symbol": "\\vec E",
        "name": "electric field",
        "meaning": "force per unit charge",
        "units": "V/m"
      },
      {
        "symbol": "\\vec B",
        "name": "magnetic field",
        "meaning": "magnetic flux density",
        "units": "T (tesla)"
      },
      {
        "symbol": "\\rho",
        "name": "charge density",
        "meaning": "electric charge per unit volume",
        "units": "C/m³"
      },
      {
        "symbol": "\\vec J",
        "name": "current density",
        "meaning": "electric current per unit area",
        "units": "A/m²"
      },
      {
        "symbol": "\\varepsilon_0",
        "name": "permittivity of free space",
        "meaning": "electric constant, 8.854×10⁻¹²",
        "units": "F/m"
      },
      {
        "symbol": "\\mu_0",
        "name": "permeability of free space",
        "meaning": "magnetic constant, 4π×10⁻⁷",
        "units": "H/m"
      },
      {
        "symbol": "F^{\\mu\\nu}",
        "name": "field-strength tensor",
        "meaning": "combines E and B into one antisymmetric tensor",
        "units": "mixed"
      }
    ],
    "connections": [
      {
        "toId": "coulomb",
        "relationship": "contains as its electrostatic (Gauss’s law) special case"
      },
      {
        "toId": "wave-equation",
        "relationship": "predicts light by reducing in vacuum to the"
      },
      {
        "toId": "yang-mills",
        "relationship": "is the abelian U(1) prototype generalized by"
      },
      {
        "toId": "mass-energy",
        "relationship": "has the Lorentz symmetry that motivated"
      }
    ]
  },
  {
    "id": "boltzmann-entropy",
    "name": "Boltzmann Entropy",
    "nickname": "the equation on his tombstone",
    "canonicalLatex": "S = k\\ln W",
    "canonicalAlt": "S equals k times the natural log of W",
    "fields": [
      "statistical-mechanics",
      "thermodynamics"
    ],
    "era": {
      "display": "1877",
      "sortKey": 1877
    },
    "oneLine": "Entropy counts the number of microscopic arrangements that look the same — disorder is just \"many ways to be this way.\"",
    "significance": "Boltzmann’s formula is the bridge between the microscopic world of atoms and the macroscopic law of thermodynamics: it defines entropy as (the log of) the number of microscopic states consistent with what we observe. It explains the second law of thermodynamics statistically — systems drift toward macrostates that can be realized in overwhelmingly more ways — and grounds the entire edifice of statistical mechanics, information theory, and our understanding of time’s arrow.",
    "symbols": [
      {
        "symbol": "S",
        "name": "entropy",
        "meaning": "a measure of how many microstates realize the macrostate",
        "units": "J/K"
      },
      {
        "symbol": "k",
        "name": "Boltzmann constant",
        "meaning": "k_B = 1.381×10⁻²³, converts microstate-count to thermodynamic entropy",
        "units": "J/K"
      },
      {
        "symbol": "W",
        "name": "multiplicity",
        "meaning": "number of microstates corresponding to the macrostate (Ω)",
        "units": "dimensionless"
      },
      {
        "symbol": "p_i",
        "name": "state probability",
        "meaning": "probability of microstate i (Gibbs form)",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "shannon-entropy",
        "relationship": "is mathematically identical (with a different constant) to"
      },
      {
        "toId": "ideal-gas",
        "relationship": "supplies the microstate counting that derives the thermodynamics of"
      },
      {
        "toId": "boltzmann-transport",
        "relationship": "increases monotonically under the dynamics of"
      }
    ]
  },
  {
    "id": "boltzmann-transport",
    "name": "Boltzmann Transport Equation",
    "nickname": "the bookkeeping of a trillion collisions",
    "canonicalLatex": "\\partial_t f+\\vec v\\!\\cdot\\!\\nabla_x f+\\tfrac{\\vec F}{m}\\!\\cdot\\!\\nabla_v f=\\left(\\partial_t f\\right)_{\\text{coll}}",
    "canonicalAlt": "partial-t f plus v dot grad-x f plus F over m dot grad-v f equals the collision term, partial-t f sub coll",
    "fields": [
      "statistical-mechanics",
      "physics"
    ],
    "era": {
      "display": "1872",
      "sortKey": 1872
    },
    "oneLine": "Tracks how the distribution of particle positions and velocities evolves as they stream and collide.",
    "significance": "The Boltzmann transport equation is the master equation of kinetic theory: it describes a gas not particle-by-particle but through the evolving distribution of velocities, bridging microscopic mechanics and macroscopic transport. From it flow the laws of viscosity, heat conduction, and electrical conductivity, the hydrodynamic (Navier–Stokes) equations, and Boltzmann’s H-theorem explaining irreversibility. It remains the workhorse for rarefied gases, neutron transport, semiconductors, plasmas, and radiative transfer.",
    "symbols": [
      {
        "symbol": "f",
        "name": "distribution function",
        "meaning": "density of particles in position–velocity (phase) space, f(x,v,t)",
        "units": "s³/m⁶"
      },
      {
        "symbol": "\\vec v",
        "name": "velocity",
        "meaning": "particle velocity coordinate",
        "units": "m/s"
      },
      {
        "symbol": "\\vec F",
        "name": "external force",
        "meaning": "force on a particle (e.g. electric, gravitational)",
        "units": "N"
      },
      {
        "symbol": "m",
        "name": "particle mass",
        "meaning": "mass of one particle",
        "units": "kg"
      },
      {
        "symbol": "\\tau",
        "name": "relaxation time",
        "meaning": "mean time between collisions (BGK model)",
        "units": "s"
      },
      {
        "symbol": "\\sigma",
        "name": "cross-section",
        "meaning": "effective collision area",
        "units": "m²"
      }
    ],
    "connections": [
      {
        "toId": "boltzmann-entropy",
        "relationship": "provides the dynamical H-theorem proof of the second law behind"
      },
      {
        "toId": "navier-stokes",
        "relationship": "derives via Chapman–Enskog the hydrodynamic equations"
      },
      {
        "toId": "ideal-gas",
        "relationship": "has the Maxwell–Boltzmann equilibrium underlying"
      }
    ]
  },
  {
    "id": "heat-equation",
    "name": "The Heat / Diffusion Equation",
    "nickname": "the equation of smoothing and spreading",
    "canonicalLatex": "\\partial_t u = \\alpha\\nabla^2 u",
    "canonicalAlt": "the time derivative of u equals alpha times the Laplacian of u",
    "fields": [
      "pde",
      "physics"
    ],
    "era": {
      "display": "1822",
      "sortKey": 1822
    },
    "oneLine": "How heat (or anything that diffuses) flows from hot to cold, always smoothing bumps away.",
    "significance": "The heat equation is the prototype parabolic PDE and the universal law of diffusion: it governs heat conduction, the spreading of dye or pollutants, the diffusion of probability (Brownian motion), and — via a change of variables — option pricing. It encodes irreversibility (the arrow of time) directly, smooths any initial data instantly, and was the problem for which Fourier invented his series. Its solution operator, the Gaussian heat kernel, recurs throughout mathematics and physics.",
    "symbols": [
      {
        "symbol": "u",
        "name": "temperature / concentration",
        "meaning": "the diffusing quantity",
        "units": "K or mol/m³"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "the time coordinate",
        "units": "s"
      },
      {
        "symbol": "\\alpha",
        "name": "thermal diffusivity",
        "meaning": "how fast the medium spreads heat (D for diffusion)",
        "units": "m²/s"
      },
      {
        "symbol": "\\nabla^2",
        "name": "Laplacian",
        "meaning": "measures how a point differs from its neighbours’ average",
        "units": "1/m²"
      }
    ],
    "connections": [
      {
        "toId": "fourier",
        "relationship": "is the very problem that motivated"
      },
      {
        "toId": "black-scholes",
        "relationship": "is, after a change of variables, identical to"
      },
      {
        "toId": "normal-distribution",
        "relationship": "has the Gaussian heat kernel that is the density of"
      },
      {
        "toId": "schrodinger",
        "relationship": "becomes, under imaginary-time rotation, the"
      }
    ]
  },
  {
    "id": "navier-stokes",
    "name": "Navier–Stokes Equations",
    "nickname": "the unsolved equations of flow",
    "canonicalLatex": "\\rho\\!\\left(\\partial_t\\vec v+\\vec v\\!\\cdot\\!\\nabla\\vec v\\right)=-\\nabla p+\\mu\\nabla^2\\vec v+\\vec f",
    "canonicalAlt": "rho times the quantity partial-t v plus v dot grad v, equals minus grad p plus mu times the Laplacian of v plus the body force f",
    "fields": [
      "fluids",
      "physics"
    ],
    "era": {
      "display": "1845",
      "sortKey": 1845
    },
    "oneLine": "Newton’s second law written for every drop of a fluid — exact, ubiquitous, and famously not fully understood.",
    "significance": "The Navier–Stokes equations are Newton’s second law applied to a continuous fluid, governing essentially all flow: weather and climate, blood and oceans, aircraft and pipelines. They are extraordinarily successful in practice yet mathematically formidable: whether smooth 3-D solutions always exist (no finite-time blow-up) is a Clay Millennium Prize problem. They are also the home of turbulence, called the most important unsolved problem of classical physics.",
    "symbols": [
      {
        "symbol": "\\vec v",
        "name": "velocity field",
        "meaning": "fluid velocity at each point and time",
        "units": "m/s"
      },
      {
        "symbol": "\\rho",
        "name": "density",
        "meaning": "mass per unit volume of the fluid",
        "units": "kg/m³"
      },
      {
        "symbol": "p",
        "name": "pressure",
        "meaning": "isotropic internal pressure",
        "units": "Pa"
      },
      {
        "symbol": "\\mu",
        "name": "dynamic viscosity",
        "meaning": "resistance to shearing/internal friction",
        "units": "Pa·s"
      },
      {
        "symbol": "\\nu",
        "name": "kinematic viscosity",
        "meaning": "μ/ρ",
        "units": "m²/s"
      },
      {
        "symbol": "\\vec f",
        "name": "body force",
        "meaning": "force per unit volume (gravity, etc.)",
        "units": "N/m³"
      },
      {
        "symbol": "\\vec\\omega",
        "name": "vorticity",
        "meaning": "local spin of the fluid, ∇×v",
        "units": "1/s"
      }
    ],
    "connections": [
      {
        "toId": "newton-second",
        "relationship": "is the continuum-fluid form of"
      },
      {
        "toId": "boltzmann-transport",
        "relationship": "emerges as the hydrodynamic limit of"
      },
      {
        "toId": "heat-equation",
        "relationship": "contains the viscous diffusion term shared with"
      },
      {
        "toId": "logistic-map",
        "relationship": "exhibits routes to chaos studied via simple models like"
      }
    ]
  },
  {
    "id": "normal-distribution",
    "name": "The Normal Distribution",
    "nickname": "the bell curve",
    "canonicalLatex": "f(x)=\\dfrac{1}{\\sqrt{2\\pi\\sigma^2}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}",
    "canonicalAlt": "f of x equals one over the square root of two pi sigma squared, times e to the minus, x minus mu squared over two sigma squared",
    "fields": [
      "statistics",
      "probability"
    ],
    "era": {
      "display": "1809",
      "sortKey": 1809
    },
    "oneLine": "The bell-shaped curve that emerges whenever many small, independent effects add up.",
    "significance": "The normal distribution is the default model of variation and error because of the central limit theorem: sums of many independent influences converge to it regardless of their individual shapes. This universality makes it the foundation of statistical inference, measurement error, quality control, and the entire machinery of confidence intervals and hypothesis tests. It is also the unique maximum-entropy distribution for a given mean and variance, and the stationary state of diffusion.",
    "symbols": [
      {
        "symbol": "x",
        "name": "variable",
        "meaning": "the value of the random quantity",
        "units": "any"
      },
      {
        "symbol": "\\mu",
        "name": "mean",
        "meaning": "center of the distribution (where the peak sits)",
        "units": "same as x"
      },
      {
        "symbol": "\\sigma",
        "name": "standard deviation",
        "meaning": "spread/width of the bell",
        "units": "same as x"
      },
      {
        "symbol": "\\sigma^2",
        "name": "variance",
        "meaning": "square of the standard deviation",
        "units": "(units of x)²"
      },
      {
        "symbol": "z",
        "name": "z-score",
        "meaning": "number of standard deviations from the mean",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "heat-equation",
        "relationship": "has as its density the Gaussian kernel of"
      },
      {
        "toId": "bayes",
        "relationship": "serves as the conjugate likelihood/prior workhorse in"
      },
      {
        "toId": "shannon-entropy",
        "relationship": "is the maximum-entropy distribution measured by"
      },
      {
        "toId": "black-scholes",
        "relationship": "supplies the log-normal price model assumed by"
      }
    ]
  },
  {
    "id": "bayes",
    "name": "Bayes' Theorem",
    "nickname": "the mathematics of updating your mind",
    "canonicalLatex": "P(A\\mid B)=\\dfrac{P(B\\mid A)\\,P(A)}{P(B)}",
    "canonicalAlt": "P of A given B equals P of B given A times P of A, divided by P of B",
    "fields": [
      "statistics",
      "probability"
    ],
    "era": {
      "display": "1763",
      "sortKey": 1763
    },
    "oneLine": "The exact rule for revising your belief in something once you see new evidence.",
    "significance": "Bayes’ theorem is the logic of evidence: it tells you precisely how to update the probability of a hypothesis given new data, weighting the data’s likelihood against your prior belief and the base rate. It underpins modern statistics, machine learning, medical diagnosis, spam filtering, and scientific inference, and it crisply explains the base-rate fallacy — why even a very accurate test can mostly raise false alarms for a rare condition.",
    "symbols": [
      {
        "symbol": "P(A)",
        "name": "prior",
        "meaning": "probability of A before seeing the evidence",
        "units": "dimensionless (0–1)"
      },
      {
        "symbol": "P(A\\mid B)",
        "name": "posterior",
        "meaning": "updated probability of A after observing B",
        "units": "dimensionless (0–1)"
      },
      {
        "symbol": "P(B\\mid A)",
        "name": "likelihood",
        "meaning": "probability of the evidence B if A were true",
        "units": "dimensionless (0–1)"
      },
      {
        "symbol": "P(B)",
        "name": "evidence / marginal",
        "meaning": "total probability of observing B (normalizer)",
        "units": "dimensionless (0–1)"
      },
      {
        "symbol": "\\theta",
        "name": "parameter/hypothesis",
        "meaning": "the unknown being inferred (inference form)",
        "units": "varies"
      }
    ],
    "connections": [
      {
        "toId": "normal-distribution",
        "relationship": "uses Gaussian likelihoods/priors as the conjugate workhorse of"
      },
      {
        "toId": "shannon-entropy",
        "relationship": "updates beliefs by information gain measured with"
      },
      {
        "toId": "logarithms",
        "relationship": "is computed in log-space (log-odds, log-likelihood) using"
      }
    ]
  },
  {
    "id": "shannon-entropy",
    "name": "Shannon Information Entropy",
    "nickname": "the equation that measured information",
    "canonicalLatex": "H=-\\sum_i p_i\\log p_i",
    "canonicalAlt": "H equals minus the sum over i of p sub i times log p sub i",
    "fields": [
      "information-theory",
      "mathematics"
    ],
    "era": {
      "display": "1948",
      "sortKey": 1948
    },
    "oneLine": "Measures information as the average surprise of an outcome — and sets the hard limit on how much you can compress or transmit.",
    "significance": "Shannon entropy founded information theory by giving \"information\" a precise, quantitative meaning: the average uncertainty (in bits) of a random source. It sets the absolute limits of data compression (the source-coding theorem) and reliable communication over noisy channels (the channel-coding theorem), underlying every modem, hard drive, phone, and streaming service. Mathematically identical to Boltzmann–Gibbs entropy, it bridges physics, statistics, and computation.",
    "symbols": [
      {
        "symbol": "H",
        "name": "entropy",
        "meaning": "average information/uncertainty of the source",
        "units": "bits (log₂) or nats (ln)"
      },
      {
        "symbol": "p_i",
        "name": "probability",
        "meaning": "probability of outcome/symbol i",
        "units": "dimensionless"
      },
      {
        "symbol": "I(X;Y)",
        "name": "mutual information",
        "meaning": "information one variable carries about another",
        "units": "bits"
      },
      {
        "symbol": "C",
        "name": "channel capacity",
        "meaning": "maximum reliable transmission rate",
        "units": "bits per use"
      }
    ],
    "connections": [
      {
        "toId": "boltzmann-entropy",
        "relationship": "is mathematically identical (different units) to"
      },
      {
        "toId": "logarithms",
        "relationship": "requires the additive-over-independence logarithm of"
      },
      {
        "toId": "bayes",
        "relationship": "measures the information gained when updating with"
      },
      {
        "toId": "normal-distribution",
        "relationship": "is the maximum-entropy distribution at fixed variance, namely"
      }
    ]
  },
  {
    "id": "mass-energy",
    "name": "Mass–Energy Equivalence",
    "nickname": "the most famous equation in the world",
    "canonicalLatex": "E=mc^2",
    "canonicalAlt": "E equals m c squared",
    "fields": [
      "relativity",
      "physics"
    ],
    "era": {
      "display": "1905",
      "sortKey": 1905
    },
    "oneLine": "Mass and energy are the same thing in different clothes; a tiny mass holds a tremendous amount of energy.",
    "significance": "Einstein’s relation overturned the separate conservation laws of mass and energy, merging them into one. It explains why the Sun shines (mass converts to radiant energy), powers nuclear reactors and weapons, and is confirmed in every particle collision where energy turns into new matter. The huge factor c² means even minuscule mass changes release enormous energy, reshaping energy, warfare, and cosmology.",
    "symbols": [
      {
        "symbol": "E",
        "name": "energy",
        "meaning": "total or rest energy of the body",
        "units": "J"
      },
      {
        "symbol": "m",
        "name": "mass",
        "meaning": "rest (invariant) mass",
        "units": "kg"
      },
      {
        "symbol": "c",
        "name": "speed of light",
        "meaning": "universal speed limit, 2.998×10⁸ m/s",
        "units": "m/s"
      },
      {
        "symbol": "p",
        "name": "momentum",
        "meaning": "relativistic momentum γmv",
        "units": "kg·m/s"
      },
      {
        "symbol": "\\gamma",
        "name": "Lorentz factor",
        "meaning": "time-dilation/energy factor 1/√(1−v²/c²)",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "newton-second",
        "relationship": "extends to high speed the dynamics of"
      },
      {
        "toId": "einstein-field",
        "relationship": "is generalized so that all energy gravitates in"
      },
      {
        "toId": "planck-einstein",
        "relationship": "gives massless photons E = pc, consistent with"
      },
      {
        "toId": "dirac",
        "relationship": "has its $E^2=(pc)^2+(mc^2)^2$ linearized by"
      }
    ]
  },
  {
    "id": "einstein-field",
    "name": "Einstein Field Equations",
    "nickname": "spacetime tells matter how to move; matter tells spacetime how to curve",
    "canonicalLatex": "G_{\\mu\\nu}+\\Lambda g_{\\mu\\nu}=\\dfrac{8\\pi G}{c^4}T_{\\mu\\nu}",
    "canonicalAlt": "G mu nu plus capital-lambda g mu nu equals eight pi G over c to the fourth, times T mu nu",
    "fields": [
      "relativity",
      "physics"
    ],
    "era": {
      "display": "1915",
      "sortKey": 1915
    },
    "oneLine": "Gravity is not a force but the curvature of spacetime, shaped by everything that carries energy.",
    "significance": "General relativity replaced Newton’s force of gravity with the geometry of spacetime: mass and energy curve spacetime, and objects follow the straightest available paths through that curvature. It predicts gravitational lensing, black holes, the expansion of the universe, and gravitational waves — all confirmed — and is essential to GPS. It remains our best theory of gravity and the framework for cosmology.",
    "symbols": [
      {
        "symbol": "G_{\\mu\\nu}",
        "name": "Einstein tensor",
        "meaning": "encodes spacetime curvature relevant to gravity",
        "units": "1/m²"
      },
      {
        "symbol": "g_{\\mu\\nu}",
        "name": "metric tensor",
        "meaning": "defines distances and times — the geometry itself",
        "units": "dimensionless"
      },
      {
        "symbol": "T_{\\mu\\nu}",
        "name": "stress–energy tensor",
        "meaning": "density and flux of energy and momentum (the source)",
        "units": "J/m³"
      },
      {
        "symbol": "\\Lambda",
        "name": "cosmological constant",
        "meaning": "vacuum energy / dark energy term",
        "units": "1/m²"
      },
      {
        "symbol": "R_{\\mu\\nu}",
        "name": "Ricci tensor",
        "meaning": "a contraction of the full curvature tensor",
        "units": "1/m²"
      },
      {
        "symbol": "R",
        "name": "Ricci scalar",
        "meaning": "the fully contracted scalar curvature",
        "units": "1/m²"
      }
    ],
    "connections": [
      {
        "toId": "gravitation",
        "relationship": "reduces in the weak-field limit to"
      },
      {
        "toId": "mass-energy",
        "relationship": "promotes to a gravitational source the energy of"
      },
      {
        "toId": "pythagoras",
        "relationship": "generalizes to curved spacetime the distance law of"
      },
      {
        "toId": "euler-lagrange",
        "relationship": "is derived by varying the Einstein–Hilbert action via"
      }
    ]
  },
  {
    "id": "planck-einstein",
    "name": "Planck–Einstein Relation",
    "nickname": "the equation that quantized light",
    "canonicalLatex": "E=h\\nu",
    "canonicalAlt": "E equals h nu",
    "fields": [
      "quantum",
      "physics"
    ],
    "era": {
      "display": "1900–1905",
      "sortKey": 1900
    },
    "oneLine": "Light comes in discrete packets whose energy is set by their frequency — the birth of quantum theory.",
    "significance": "The Planck–Einstein relation introduced the quantum: energy exchanged with light is not continuous but comes in packets (\"quanta,\" later photons) of size hν. It resolved the ultraviolet catastrophe of blackbody radiation and explained the photoelectric effect, launching quantum mechanics. The constant h is the fundamental scale separating classical from quantum behavior and recurs throughout modern physics.",
    "symbols": [
      {
        "symbol": "E",
        "name": "photon energy",
        "meaning": "energy of a single quantum of light",
        "units": "J (or eV)"
      },
      {
        "symbol": "h",
        "name": "Planck constant",
        "meaning": "the quantum of action, 6.626×10⁻³⁴",
        "units": "J·s"
      },
      {
        "symbol": "\\nu",
        "name": "frequency",
        "meaning": "oscillation frequency of the light",
        "units": "Hz"
      },
      {
        "symbol": "\\hbar",
        "name": "reduced Planck constant",
        "meaning": "h/2π",
        "units": "J·s"
      },
      {
        "symbol": "\\lambda",
        "name": "wavelength",
        "meaning": "wavelength of the light, c/ν",
        "units": "m"
      }
    ],
    "connections": [
      {
        "toId": "de-broglie",
        "relationship": "is paired with the matter-wave relation of"
      },
      {
        "toId": "schrodinger",
        "relationship": "supplies the energy–frequency quantization built into"
      },
      {
        "toId": "mass-energy",
        "relationship": "gives the massless photon E = pc consistent with"
      },
      {
        "toId": "boltzmann-entropy",
        "relationship": "provides the Boltzmann factor that quantization combines with from"
      }
    ]
  },
  {
    "id": "de-broglie",
    "name": "De Broglie Relation",
    "nickname": "matter is a wave",
    "canonicalLatex": "\\lambda=\\dfrac{h}{p}",
    "canonicalAlt": "lambda equals h over p",
    "fields": [
      "quantum",
      "physics"
    ],
    "era": {
      "display": "1924",
      "sortKey": 1924
    },
    "oneLine": "Every particle is also a wave, with a wavelength set by its momentum.",
    "significance": "De Broglie proposed that wave–particle duality, known for light, applies to all matter: an electron, atom, or baseball has a wavelength λ = h/p. This unified the dual nature of light and matter, explained why atomic orbits are quantized (standing electron waves), and directly inspired Schrödinger’s wave equation. It is confirmed daily in electron microscopy and neutron/atom interferometry.",
    "symbols": [
      {
        "symbol": "\\lambda",
        "name": "de Broglie wavelength",
        "meaning": "wavelength associated with a particle",
        "units": "m"
      },
      {
        "symbol": "h",
        "name": "Planck constant",
        "meaning": "6.626×10⁻³⁴ J·s",
        "units": "J·s"
      },
      {
        "symbol": "p",
        "name": "momentum",
        "meaning": "particle momentum mv (or relativistic γmv)",
        "units": "kg·m/s"
      },
      {
        "symbol": "\\vec k",
        "name": "wavevector",
        "meaning": "direction and 2π/λ of the wave",
        "units": "1/m"
      }
    ],
    "connections": [
      {
        "toId": "planck-einstein",
        "relationship": "extends to matter the photon relation of"
      },
      {
        "toId": "schrodinger",
        "relationship": "is the plane-wave solution that motivated"
      },
      {
        "toId": "fourier",
        "relationship": "makes position and momentum conjugate variables of"
      },
      {
        "toId": "ideal-gas",
        "relationship": "sets via the thermal wavelength the quantum-degeneracy limit of"
      }
    ]
  },
  {
    "id": "schrodinger",
    "name": "The Schrödinger Equation",
    "nickname": "the F = ma of the quantum world",
    "canonicalLatex": "i\\hbar\\,\\partial_t\\psi=\\hat H\\psi",
    "canonicalAlt": "i h-bar times the time derivative of psi equals H-hat psi",
    "fields": [
      "quantum",
      "physics"
    ],
    "era": {
      "display": "1926",
      "sortKey": 1926
    },
    "oneLine": "The master equation of quantum mechanics: it dictates how a particle’s wavefunction evolves in time.",
    "significance": "The Schrödinger equation is to quantum mechanics what Newton’s second law is to classical mechanics — the equation of motion for the wavefunction. It quantizes energy levels (explaining atomic spectra, chemical bonds, and the periodic table), predicts tunneling, and underlies all of chemistry, condensed-matter physics, and quantum technology. Its solutions are probability amplitudes whose squared magnitude gives the odds of finding a particle.",
    "symbols": [
      {
        "symbol": "\\psi",
        "name": "wavefunction",
        "meaning": "complex amplitude whose |ψ|² gives probability density",
        "units": "depends on dimension (e.g. m⁻³ᐟ²)"
      },
      {
        "symbol": "i",
        "name": "imaginary unit",
        "meaning": "i² = −1; makes the equation generate oscillation/phase",
        "units": "dimensionless"
      },
      {
        "symbol": "\\hbar",
        "name": "reduced Planck constant",
        "meaning": "h/2π, the quantum of action",
        "units": "J·s"
      },
      {
        "symbol": "\\hat H",
        "name": "Hamiltonian operator",
        "meaning": "total energy operator (kinetic + potential)",
        "units": "J"
      },
      {
        "symbol": "V",
        "name": "potential energy",
        "meaning": "the potential the particle moves in",
        "units": "J"
      },
      {
        "symbol": "E",
        "name": "energy eigenvalue",
        "meaning": "allowed energy of a stationary state",
        "units": "J"
      }
    ],
    "connections": [
      {
        "toId": "de-broglie",
        "relationship": "is the wave equation whose plane-wave solutions are the matter waves of"
      },
      {
        "toId": "planck-einstein",
        "relationship": "builds in the energy–frequency quantization of"
      },
      {
        "toId": "dirac",
        "relationship": "is the non-relativistic limit of"
      },
      {
        "toId": "heat-equation",
        "relationship": "is, under imaginary-time rotation, the"
      }
    ]
  },
  {
    "id": "dirac",
    "name": "The Dirac Equation",
    "nickname": "the equation that predicted antimatter",
    "canonicalLatex": "(i\\gamma^\\mu\\partial_\\mu-m)\\psi=0",
    "canonicalAlt": "open paren i gamma mu partial mu minus m close paren psi equals zero",
    "fields": [
      "qft",
      "quantum"
    ],
    "era": {
      "display": "1928",
      "sortKey": 1928
    },
    "oneLine": "A relativistic quantum equation for the electron that forced the existence of spin and antimatter.",
    "significance": "Dirac unified quantum mechanics with special relativity for the electron, and in doing so derived spin-½ from first principles and predicted antimatter — the positron — years before its discovery. The equation correctly gives the electron’s magnetic moment, fine structure, and is the cornerstone of quantum electrodynamics and the Standard Model’s treatment of all fermions (quarks and leptons).",
    "symbols": [
      {
        "symbol": "\\psi",
        "name": "Dirac spinor",
        "meaning": "four-component wavefunction encoding spin and particle/antiparticle",
        "units": "depends on normalization"
      },
      {
        "symbol": "\\gamma^\\mu",
        "name": "gamma matrices",
        "meaning": "four 4×4 matrices satisfying the Clifford algebra",
        "units": "dimensionless"
      },
      {
        "symbol": "\\partial_\\mu",
        "name": "spacetime derivative",
        "meaning": "derivative with respect to time and space (4-gradient)",
        "units": "1/m"
      },
      {
        "symbol": "m",
        "name": "mass",
        "meaning": "rest mass of the particle (in natural units)",
        "units": "kg (or eV/c²)"
      },
      {
        "symbol": "g^{\\mu\\nu}",
        "name": "metric",
        "meaning": "Minkowski spacetime metric",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "schrodinger",
        "relationship": "has as its non-relativistic limit the"
      },
      {
        "toId": "mass-energy",
        "relationship": "linearizes the relativistic energy relation of"
      },
      {
        "toId": "maxwell",
        "relationship": "becomes QED when minimally coupled to"
      },
      {
        "toId": "yang-mills",
        "relationship": "supplies the matter fermions coupled to the gauge fields of"
      }
    ]
  },
  {
    "id": "yang-mills",
    "name": "Yang–Mills Equations",
    "nickname": "the blueprint of the forces",
    "canonicalLatex": "D_\\mu F^{\\mu\\nu}=J^\\nu,\\ F_{\\mu\\nu}=\\partial_\\mu A_\\nu-\\partial_\\nu A_\\mu+g[A_\\mu,A_\\nu]",
    "canonicalAlt": "D mu F mu nu equals J nu, where F mu nu equals partial mu A nu minus partial nu A mu plus g times the commutator of A mu and A nu",
    "fields": [
      "qft",
      "physics"
    ],
    "era": {
      "display": "1954",
      "sortKey": 1954
    },
    "oneLine": "The generalization of Maxwell’s equations whose self-interacting force fields describe the strong and weak nuclear forces.",
    "significance": "Yang–Mills theory generalizes electromagnetism from the simple U(1) symmetry to non-commuting (non-abelian) symmetry groups, making the force-carrying fields interact with themselves. This single framework, combined with the Higgs mechanism and quark color, is the mathematical backbone of the Standard Model — the electroweak and strong interactions. Its quantum properties (asymptotic freedom, confinement) explain why quarks bind into protons, and its mathematical depth is recognized by a \\$1 million Millennium Prize.",
    "symbols": [
      {
        "symbol": "A_\\mu",
        "name": "gauge field",
        "meaning": "the force-carrying potential (matrix-valued for non-abelian groups)",
        "units": "mixed"
      },
      {
        "symbol": "F_{\\mu\\nu}",
        "name": "field strength",
        "meaning": "the non-abelian curvature, including self-interaction",
        "units": "mixed"
      },
      {
        "symbol": "D_\\mu",
        "name": "covariant derivative",
        "meaning": "derivative that respects the gauge symmetry",
        "units": "1/m"
      },
      {
        "symbol": "g",
        "name": "coupling constant",
        "meaning": "strength of the interaction (and of self-interaction)",
        "units": "dimensionless"
      },
      {
        "symbol": "T^a",
        "name": "group generators",
        "meaning": "the (non-commuting) generators of the symmetry group",
        "units": "dimensionless"
      },
      {
        "symbol": "J^\\nu",
        "name": "current",
        "meaning": "the matter source current",
        "units": "A/m²-like"
      }
    ],
    "connections": [
      {
        "toId": "maxwell",
        "relationship": "generalizes from abelian U(1) the gauge theory of"
      },
      {
        "toId": "dirac",
        "relationship": "couples to the matter fermions described by"
      },
      {
        "toId": "renormalization-group",
        "relationship": "has its asymptotic freedom revealed by"
      },
      {
        "toId": "euler-lagrange",
        "relationship": "is derived by varying its gauge-invariant Lagrangian via"
      }
    ]
  },
  {
    "id": "renormalization-group",
    "name": "RG / Beta Function",
    "nickname": "the physics of zooming in and out",
    "canonicalLatex": "\\mu\\dfrac{dg}{d\\mu}=\\beta(g)",
    "canonicalAlt": "mu times d g by d mu equals beta of g",
    "fields": [
      "qft",
      "physics"
    ],
    "era": {
      "display": "1954/1971",
      "sortKey": 1954
    },
    "oneLine": "How the effective strength of a force changes with the scale at which you look — the deep reason physics at different scales looks different.",
    "significance": "The renormalization group explains why the laws of physics look different at different length/energy scales, and why this is not a flaw but a feature. It tamed the infinities of quantum field theory, predicted the running couplings of the Standard Model (including asymptotic freedom), and — in Wilson’s hands — explained the universality of phase transitions, where wildly different systems share the same critical exponents. It is one of the deepest unifying ideas in 20th-century physics.",
    "symbols": [
      {
        "symbol": "g",
        "name": "coupling constant",
        "meaning": "the effective interaction strength",
        "units": "dimensionless"
      },
      {
        "symbol": "\\mu",
        "name": "scale",
        "meaning": "the energy or length scale at which the coupling is measured",
        "units": "energy (or 1/length)"
      },
      {
        "symbol": "\\beta(g)",
        "name": "beta function",
        "meaning": "rate of change of the coupling with scale",
        "units": "dimensionless"
      },
      {
        "symbol": "g_*",
        "name": "fixed point",
        "meaning": "a coupling value where β = 0 (scale-invariant)",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "yang-mills",
        "relationship": "reveals the asymptotic freedom of"
      },
      {
        "toId": "logistic-map",
        "relationship": "explains via a fixed point the Feigenbaum universality of"
      },
      {
        "toId": "boltzmann-entropy",
        "relationship": "organizes the critical phenomena and phase transitions described statistically by"
      },
      {
        "toId": "maxwell",
        "relationship": "makes scale-dependent the coupling of"
      }
    ]
  },
  {
    "id": "laplace-transform",
    "name": "The Laplace Transform",
    "nickname": "the engineer’s key from calculus to algebra",
    "canonicalLatex": "F(s)=\\int_0^{\\infty} f(t)\\,e^{-st}\\,dt",
    "canonicalAlt": "F of s equals the integral from zero to infinity of f of t times e to the minus s t, d t",
    "fields": [
      "mathematics",
      "analysis"
    ],
    "era": {
      "display": "1785",
      "sortKey": 1785
    },
    "oneLine": "A machine that turns differential equations into algebra by trading the time domain for a complex-frequency domain.",
    "significance": "The Laplace transform converts the calculus of how systems evolve in time — differential equations — into ordinary algebra in a complex variable s, automatically folding in initial conditions. It is the foundational tool of control theory and electrical engineering: transfer functions, stability analysis, and the entire pole–zero picture of how systems respond are written in the s-plane. It generalizes the Fourier transform to decaying/growing signals and is the bridge between transient analysis and steady-state frequency response.",
    "symbols": [
      {
        "symbol": "f(t)",
        "name": "time-domain signal",
        "meaning": "the function of time being transformed (t ≥ 0)",
        "units": "any"
      },
      {
        "symbol": "F(s)",
        "name": "s-domain transform",
        "meaning": "the transformed function of the complex variable s",
        "units": "units of f × time"
      },
      {
        "symbol": "s",
        "name": "complex frequency",
        "meaning": "complex variable s = σ + iω",
        "units": "1/time"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "the time variable (integration from 0)",
        "units": "s"
      },
      {
        "symbol": "\\sigma",
        "name": "real part of s",
        "meaning": "damping/growth rate; controls convergence",
        "units": "1/s"
      },
      {
        "symbol": "\\omega",
        "name": "angular frequency",
        "meaning": "imaginary part of s (oscillation rate)",
        "units": "rad/s"
      },
      {
        "symbol": "H(s)",
        "name": "transfer function",
        "meaning": "ratio of output to input transforms",
        "units": "depends"
      }
    ],
    "connections": [
      {
        "toId": "fourier",
        "relationship": "generalizes to complex frequency the"
      },
      {
        "toId": "derivative",
        "relationship": "converts into multiplication by s the"
      },
      {
        "toId": "heat-equation",
        "relationship": "turns into algebra (via the resolvent) the evolution of the"
      },
      {
        "toId": "logarithms",
        "relationship": "shares the calculus-to-algebra spirit of"
      }
    ]
  },
  {
    "id": "mandelbrot",
    "name": "The Mandelbrot Iteration",
    "nickname": "the most complex object in mathematics",
    "canonicalLatex": "z_{n+1}=z_n^2+c",
    "canonicalAlt": "z sub n plus one equals z sub n squared plus c",
    "fields": [
      "nonlinear-dynamics",
      "mathematics"
    ],
    "era": {
      "display": "1980",
      "sortKey": 1980
    },
    "oneLine": "A one-line rule on complex numbers that generates infinite, self-similar complexity — the icon of fractals.",
    "significance": "The Mandelbrot set shows that endless, intricate, self-similar structure can arise from the simplest nonlinear rule, $z \\to z^2 + c$, iterated on the complex plane. It is the master catalog of Julia sets, the visual emblem of chaos and fractal geometry, and the complexification of the logistic map — its real-axis slice contains the entire period-doubling route to chaos. It made fractals a household idea and connects elementary iteration to deep questions in complex dynamics.",
    "symbols": [
      {
        "symbol": "z_n",
        "name": "iterate",
        "meaning": "the nth value in the orbit (a complex number), starting z₀ = 0",
        "units": "dimensionless"
      },
      {
        "symbol": "c",
        "name": "parameter",
        "meaning": "a fixed complex number; one point of the picture",
        "units": "dimensionless"
      },
      {
        "symbol": "M",
        "name": "Mandelbrot set",
        "meaning": "the set of c for which the orbit stays bounded",
        "units": "a region of ℂ"
      },
      {
        "symbol": "i",
        "name": "imaginary unit",
        "meaning": "i² = −1; the vertical axis of the complex plane",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "logistic-map",
        "relationship": "complexifies, containing on its real axis the"
      },
      {
        "toId": "renormalization-group",
        "relationship": "has self-similar copies explained by the renormalization of"
      },
      {
        "toId": "euler-identity",
        "relationship": "iterates in the complex plane built on"
      }
    ]
  },
  {
    "id": "black-scholes",
    "name": "The Black–Scholes Equation",
    "nickname": "the equation that priced risk",
    "canonicalLatex": "\\partial_t V+\\tfrac12\\sigma^2 S^2\\partial_S^2 V+rS\\partial_S V-rV=0",
    "canonicalAlt": "partial-t V plus one-half sigma squared S squared times the second S-derivative of V, plus r S times the S-derivative of V, minus r V, equals zero",
    "fields": [
      "finance",
      "pde"
    ],
    "era": {
      "display": "1973",
      "sortKey": 1973
    },
    "oneLine": "A way to put a fair price on a financial option by continuously hedging away its risk.",
    "significance": "Black–Scholes gave the first widely accepted, theoretically grounded formula for pricing options, launching the modern multi-trillion-dollar derivatives industry. Its core idea — that a risky payoff can be replicated (and thus priced) by a continuously rebalanced portfolio, eliminating risk — reshaped quantitative finance. Mathematically it is the heat equation in disguise, and it earned the 1997 Nobel Prize. Its assumptions and famous failures (the volatility \"smile,\" crashes) are equally instructive.",
    "symbols": [
      {
        "symbol": "V",
        "name": "option value",
        "meaning": "price of the derivative as a function of S and t",
        "units": "currency"
      },
      {
        "symbol": "S",
        "name": "underlying price",
        "meaning": "current price of the underlying asset (stock)",
        "units": "currency"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "current time (T is expiry)",
        "units": "years"
      },
      {
        "symbol": "\\sigma",
        "name": "volatility",
        "meaning": "standard deviation of the asset’s returns",
        "units": "per √year"
      },
      {
        "symbol": "r",
        "name": "risk-free rate",
        "meaning": "continuously compounded interest rate",
        "units": "per year"
      },
      {
        "symbol": "K",
        "name": "strike price",
        "meaning": "agreed exercise price of the option",
        "units": "currency"
      },
      {
        "symbol": "N",
        "name": "normal CDF",
        "meaning": "cumulative standard normal distribution",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "heat-equation",
        "relationship": "transforms by a change of variables exactly into the"
      },
      {
        "toId": "normal-distribution",
        "relationship": "prices options using the cumulative Gaussian of the"
      },
      {
        "toId": "logarithms",
        "relationship": "models log-returns and discounts continuously using"
      }
    ]
  },
  {
    "id": "kdv",
    "name": "Korteweg–de Vries Equation",
    "nickname": "the equation of the solitary wave",
    "canonicalLatex": "\\partial_t u+u\\,\\partial_x u+\\partial_x^3 u=0",
    "canonicalAlt": "partial-t u plus u times partial-x u plus the third x-derivative of u, equals zero",
    "fields": [
      "pde",
      "nonlinear-dynamics"
    ],
    "era": {
      "display": "1895",
      "sortKey": 1895
    },
    "oneLine": "A wave equation balancing steepening against spreading so perfectly that lone humps — solitons — travel undistorted and survive collisions.",
    "significance": "The KdV equation models shallow-water waves and was the birthplace of the soliton: a solitary wave whose shape is preserved by an exact balance between nonlinear steepening and dispersive spreading. Astonishingly, solitons pass through each other unchanged, and KdV is exactly integrable — possessing infinitely many conservation laws and solvable by the inverse scattering transform. It opened the entire modern field of integrable systems, linking water waves to optics, plasmas, and deep mathematics.",
    "symbols": [
      {
        "symbol": "u",
        "name": "wave amplitude",
        "meaning": "the wave profile (e.g. water-surface height)",
        "units": "depends (e.g. m)"
      },
      {
        "symbol": "t",
        "name": "time",
        "meaning": "time coordinate",
        "units": "s"
      },
      {
        "symbol": "x",
        "name": "position",
        "meaning": "spatial coordinate along the channel",
        "units": "m"
      },
      {
        "symbol": "c",
        "name": "wave speed",
        "meaning": "soliton speed, proportional to its amplitude",
        "units": "m/s"
      },
      {
        "symbol": "H",
        "name": "Hamiltonian",
        "meaning": "conserved energy functional generating the flow",
        "units": "energy"
      }
    ],
    "connections": [
      {
        "toId": "schrodinger",
        "relationship": "is solved via the spectrum of the Schrödinger operator in"
      },
      {
        "toId": "wave-equation",
        "relationship": "adds nonlinearity and dispersion to the linear"
      },
      {
        "toId": "fourier",
        "relationship": "is linearized by a nonlinear analogue (inverse scattering) of"
      }
    ]
  },
  {
    "id": "lotka-volterra",
    "name": "Lotka–Volterra Equations",
    "nickname": "the predator–prey equations",
    "canonicalLatex": "\\dot x=\\alpha x-\\beta xy,\\quad \\dot y=\\delta xy-\\gamma y",
    "canonicalAlt": "x-dot equals alpha x minus beta x y; y-dot equals delta x y minus gamma y",
    "fields": [
      "mathematical-biology",
      "nonlinear-dynamics"
    ],
    "era": {
      "display": "1925–1926",
      "sortKey": 1925
    },
    "oneLine": "A pair of equations whose feedback between predators and prey produces perpetual, linked population cycles.",
    "significance": "The Lotka–Volterra equations are the foundational model of mathematical ecology, showing how the simple feedback between predators and prey generates self-sustaining population oscillations — neither species in control, each driving the other. They introduced nonlinear dynamical-systems thinking to biology, explain counterintuitive effects (like why pesticides can boost pests), and generalize into the competitive and replicator dynamics central to ecology, epidemiology, and evolutionary game theory.",
    "symbols": [
      {
        "symbol": "x",
        "name": "prey population",
        "meaning": "density of the prey species",
        "units": "individuals (or density)"
      },
      {
        "symbol": "y",
        "name": "predator population",
        "meaning": "density of the predator species",
        "units": "individuals (or density)"
      },
      {
        "symbol": "\\alpha",
        "name": "prey growth rate",
        "meaning": "natural per-capita prey birth rate (no predators)",
        "units": "1/time"
      },
      {
        "symbol": "\\beta",
        "name": "predation rate",
        "meaning": "rate prey are removed per predator encounter",
        "units": "1/(time·predator)"
      },
      {
        "symbol": "\\delta",
        "name": "predator gain",
        "meaning": "predator growth per prey consumed",
        "units": "1/(time·prey)"
      },
      {
        "symbol": "\\gamma",
        "name": "predator death rate",
        "meaning": "natural per-capita predator death rate (no prey)",
        "units": "1/time"
      }
    ],
    "connections": [
      {
        "toId": "logistic-map",
        "relationship": "shares density-dependent population dynamics with the discrete"
      },
      {
        "toId": "euler-lagrange",
        "relationship": "has a hidden Hamiltonian structure akin to that derived from"
      },
      {
        "toId": "navier-stokes",
        "relationship": "exhibits nonlinear oscillations and pattern formation studied alongside"
      }
    ]
  },
  {
    "id": "logistic-map",
    "name": "The Logistic Map",
    "nickname": "the simplest equation that makes chaos",
    "canonicalLatex": "x_{n+1} = r\\,x_n(1-x_n)",
    "canonicalAlt": "x sub n plus one equals r times x sub n times the quantity one minus x sub n",
    "fields": [
      "nonlinear-dynamics",
      "mathematics"
    ],
    "era": {
      "display": "1976",
      "sortKey": 1976
    },
    "oneLine": "A one-line population rule that proves simple, exact systems can be utterly unpredictable.",
    "significance": "The logistic map is the canonical example of deterministic chaos: a quadratic recurrence with no randomness whose long-term behaviour can be exactly periodic or genuinely unpredictable depending on a single parameter. Its period-doubling route to chaos exhibits the universal Feigenbaum constants, found in real physical experiments, making it a Rosetta Stone linking nonlinear dynamics, statistical mechanics, and the renormalization group.",
    "symbols": [
      {
        "symbol": "x_n",
        "name": "state at step n",
        "meaning": "population as a fraction of the maximum the environment can hold, so 0 ≤ xₙ ≤ 1",
        "units": "dimensionless"
      },
      {
        "symbol": "r",
        "name": "growth (boom) parameter",
        "meaning": "controls reproduction rate; the bifurcation parameter, studied on 0 ≤ r ≤ 4",
        "units": "dimensionless"
      },
      {
        "symbol": "n",
        "name": "generation index",
        "meaning": "discrete time step (integer)",
        "units": "dimensionless"
      },
      {
        "symbol": "x_*",
        "name": "fixed point",
        "meaning": "a state that maps to itself, x* = f_r(x*)",
        "units": "dimensionless"
      },
      {
        "symbol": "\\lambda",
        "name": "Lyapunov exponent",
        "meaning": "mean exponential rate of separation of nearby trajectories; λ > 0 signals chaos",
        "units": "per step (dimensionless)"
      },
      {
        "symbol": "\\delta",
        "name": "Feigenbaum δ",
        "meaning": "universal ratio of successive period-doubling intervals, ≈ 4.66920",
        "units": "dimensionless"
      },
      {
        "symbol": "\\alpha",
        "name": "Feigenbaum α",
        "meaning": "universal attractor-rescaling constant, ≈ 2.50291",
        "units": "dimensionless"
      }
    ],
    "connections": [
      {
        "toId": "mandelbrot",
        "relationship": "is the real-axis slice of"
      },
      {
        "toId": "renormalization-group",
        "relationship": "has its universality explained by the"
      },
      {
        "toId": "lotka-volterra",
        "relationship": "is a discrete-time population cousin of"
      },
      {
        "toId": "shannon-entropy",
        "relationship": "has its chaos quantified by entropy, kin to"
      }
    ]
  }
];
