/**
 * Generates src/content/meta.generated.ts — the lightweight metadata payload the
 * runtime uses for listing/search/graph views. Derived deterministically from
 * the full corpus so it can never drift from the source of truth.
 *
 * Run via `pnpm gen:meta` (wired into `predev` and `prebuild`).
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { equations, toMeta } from '../src/content/corpus';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/content/meta.generated.ts');

const metas = equations.map(toMeta);

const banner =
  '// AUTO-GENERATED by scripts/generate-meta.ts — DO NOT EDIT BY HAND.\n' +
  '// Run `pnpm gen:meta` after changing any equation\'s metadata fields.\n' +
  "import type { EquationMeta } from './types';\n\n";

const body = `export const meta: EquationMeta[] = ${JSON.stringify(metas, null, 2)};\n`;

writeFileSync(OUT, banner + body, 'utf8');
console.log(`✓  Wrote ${metas.length} equation metadata records to meta.generated.ts`);
